export const appCopy = {
  pl: {
    ride: 'Jazda', discover: 'Odkrywaj', club: 'Klub', you: 'Ty',
    greeting: 'Twój następny kilometr.', prepare: 'Wybierz aktywność i ruszaj. Ustawienia jazdy znajdziesz w kolejnym kroku.',
    live: 'Twoja jazda trwa', liveBody: 'Wróć do bieżącej sesji. Przeglądanie aplikacji nie kończy nagrywania.',
    recent: 'Ostatnia aktywność', week: 'W tym tygodniu', sample: 'Podgląd — dane przykładowe',
    map: 'Mapa', instrument: 'Licznik', session: 'Bieżąca sesja', home: 'Wróć do aplikacji',
    location: 'Pozycja dostępna', locationUnknown: 'Oczekiwanie na pozycję',
    locationNote: 'Dostępna pozycja nie potwierdza jakości ani świeżości sygnału GPS.',
    mapLoading: 'Wczytywanie podkładu mapy…', mapError: 'Podkład mapy jest niedostępny.',
    mapErrorBody: 'Dane jazdy i przyciski działają niezależnie od podkładu. Spróbuj ponownie lub przełącz na licznik.',
    mapRetry: 'Ponów mapę', search: 'Szukaj miejsc', places: 'Miejsca', noMatches: 'Brak pasujących miejsc.',
    mapOverview: 'Widok przeglądowy — brak pozycji użytkownika', selectedPlace: 'Wybrane miejsce',
    community: 'Razem na trasie.', communityBody: 'Wydarzenia, kluby i aktywność Twojej społeczności.',
    event: 'Bieżące wydarzenie', noEvent: 'Brak bieżącego wydarzenia.', communityActivity: 'Aktywność społeczności',
    account: 'Twoje kilometry. Twoje tempo.', shortcuts: 'Twoja przestrzeń', progress: 'Postępy',
    appearance: 'Wygląd', preferences: 'Preferencje', integrations: 'Połączenia', privacy: 'Prywatność', equipment: 'Zawodnik i sprzęt',
    unknown: 'Nie udało się odczytać stanu', retry: 'Spróbuj ponownie', busy: 'Przetwarzanie…',
    actionError: 'Operacja nie została potwierdzona. Spróbuj ponownie.',
    saved: 'Zapisano', save: 'Zapisz', cancel: 'Anuluj', close: 'Zamknij',
    invalidWeight: 'Podaj masę od 30 do 200 kg.', invalidHr: 'Podaj tętno od 100 do 230 bpm.',
    unavailable: 'Funkcja nie jest jeszcze dostępna.',
    finishTitle: 'Zakończyć jazdę?', finishBody: 'Ta operacja zakończy bieżącą sesję i rozpocznie jej zapis.',
    finish: 'Zakończ jazdę', hold: 'Przytrzymaj, aby zakończyć', paused: 'Przerwa w jeździe',
    pauseBody: 'Wznów tę samą sesję albo przytrzymaj zakończenie jazdy.',
    result: 'Podsumowanie jazdy', durable: 'Jazda zakończona', pending: 'Finalizacja w toku', recovery: 'Zapis wymaga uwagi',
    durableBody: 'Finalizacja jazdy została potwierdzona.',
    pendingBody: 'Nie ma jeszcze potwierdzenia finalizacji. Dane oczekujące na wysłanie nie są dowodem zakończonej synchronizacji.',
    recoveryBody: 'Nie potwierdzono bezpiecznego zakończenia. Zachowaj dane aplikacji i wróć do diagnostyki odzyskiwania.',
    missingResult: 'Brak odtworzonego wyniku. Nie zastępujemy go zerami.', back: 'Wróć do Jazdy',
    distance: 'Dystans', duration: 'Czas jazdy', elevation: 'Przewyższenie', speed: 'Prędkość', average: 'Średnia prędkość',
    share: 'Udostępnij wynik', shareTitle: 'Moja jazda · 4VELO',
  },
  en: {
    ride: 'Ride', discover: 'Discover', club: 'Club', you: 'You',
    greeting: 'Your next kilometre.', prepare: 'Choose an activity and get moving. Ride preparation comes next.',
    live: 'Your ride is in progress', liveBody: 'Return to the current session. Browsing the app does not stop recording.',
    recent: 'Latest activity', week: 'This week', sample: 'Preview — sample data',
    map: 'Map', instrument: 'Instruments', session: 'Current session', home: 'Back to the app',
    location: 'Position available', locationUnknown: 'Waiting for a position',
    locationNote: 'An available position does not confirm GPS signal quality or freshness.',
    mapLoading: 'Loading the basemap…', mapError: 'The basemap is unavailable.',
    mapErrorBody: 'Ride data and controls work independently of the basemap. Retry or switch to instruments.',
    mapRetry: 'Retry map', search: 'Search places', places: 'Places', noMatches: 'No matching places.',
    mapOverview: 'Overview — no user position', selectedPlace: 'Selected place',
    community: 'Better together.', communityBody: 'Events, clubs and activity in your community.',
    event: 'Current event', noEvent: 'No current event.', communityActivity: 'Community activity',
    account: 'Your kilometres. Your pace.', shortcuts: 'Your space', progress: 'Progress',
    appearance: 'Appearance', preferences: 'Preferences', integrations: 'Connections', privacy: 'Privacy', equipment: 'Rider and equipment',
    unknown: 'Status could not be loaded', retry: 'Try again', busy: 'Working…',
    actionError: 'The operation was not confirmed. Please try again.',
    saved: 'Saved', save: 'Save', cancel: 'Cancel', close: 'Close',
    invalidWeight: 'Enter a weight from 30 to 200 kg.', invalidHr: 'Enter a heart rate from 100 to 230 bpm.',
    unavailable: 'This feature is not available yet.',
    finishTitle: 'Finish this ride?', finishBody: 'This ends the current session and starts saving it.',
    finish: 'Finish ride', hold: 'Hold to finish', paused: 'Ride paused',
    pauseBody: 'Resume the same session or hold to finish the ride.',
    result: 'Ride summary', durable: 'Ride finished', pending: 'Finalization pending', recovery: 'Saving needs attention',
    durableBody: 'Ride finalization has been confirmed.',
    pendingBody: 'Finalization is not confirmed yet. Data waiting to upload is not evidence of completed synchronization.',
    recoveryBody: 'Safe completion was not confirmed. Keep the app data and return to recovery diagnostics.',
    missingResult: 'No recovered result is available. Unknown values are not replaced with zero.', back: 'Back to Ride',
    distance: 'Distance', duration: 'Ride time', elevation: 'Elevation gain', speed: 'Speed', average: 'Average speed',
    share: 'Share result', shareTitle: 'My ride · 4VELO',
  },
} as const;
export function getAppCopy(locale: string) { return appCopy[locale === 'pl' ? 'pl' : 'en']; }
