from django.urls import path
from .views import (
    RegisterView,
    UserProfileView,
    PasswordChangeView,
    PasswordResetRequestView,
    PasswordResetConfirmView,
    TenantBrandingView,
    TenantUpdateView,
    ImpersonateUserView,
    UserListView,
    UserDetailView,
    TenantListView,
    AuditLogListView,
    UserCreateView,
    UserUpdateView,
    UserDeleteView,
    InvitationTokenView,
    UserBulkSetStatusView,
    UserBulkChangeRoleView,
    UserBulkJobStatusView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('password/change/', PasswordChangeView.as_view(), name='password-change'),
    path('password/reset/', PasswordResetRequestView.as_view(), name='password-reset'),
    path('password/reset/confirm/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('branding/<str:tenant_id>/', TenantBrandingView.as_view(), name='tenant-branding'),
    path('branding/<str:pk>/update/', TenantUpdateView.as_view(), name='tenant-update'),
    path('impersonate/<int:target_user_id>/', ImpersonateUserView.as_view(), name='impersonate'),
    path('all/', UserListView.as_view(), name='user-list'),
    path('tenants/all/', TenantListView.as_view(), name='tenant-list'),
    path('audit-log/', AuditLogListView.as_view(), name='audit-log-list'),
    path('create/', UserCreateView.as_view(), name='user-create'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='user-update'),
    path('<int:pk>/delete/', UserDeleteView.as_view(), name='user-delete'),
    path('<int:pk>/detail/', UserDetailView.as_view(), name='user-detail'),
    path('bulk/set-status/', UserBulkSetStatusView.as_view(), name='users-bulk-set-status'),
    path('bulk/change-role/', UserBulkChangeRoleView.as_view(), name='users-bulk-change-role'),
    path('bulk/jobs/<str:job_id>/', UserBulkJobStatusView.as_view(), name='users-bulk-job-status'),
    path('invitation/', InvitationTokenView.as_view(), name='invitation'),
]
