from django.urls import path

from .export_views import user_data_export_download_view, user_data_export_view
from .mfa_views import (
    mfa_disable_view,
    mfa_enable_view,
    mfa_setup_view,
    mfa_status_view,
    mfa_verify_session_view,
)
from .views import (
    AuditLogListView,
    ImpersonateUserView,
    InvitationTokenView,
    PasswordChangeView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    PublicTenantListView,
    PushTokenRegisterView,
    RegisterView,
    TenantBrandingView,
    TenantListView,
    TenantUpdateView,
    UserBulkChangeRoleView,
    UserBulkJobStatusView,
    UserBulkSetStatusView,
    UserCreateView,
    UserDeleteView,
    UserDetailView,
    UserListView,
    UserPreferencesView,
    UserProfileView,
    UserUpdateView,
)

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("preferences/", UserPreferencesView.as_view(), name="user-preferences"),
    path("push/register/", PushTokenRegisterView.as_view(), name="user-push-register"),
    path("password/change/", PasswordChangeView.as_view(), name="password-change"),
    path("password/reset/", PasswordResetRequestView.as_view(), name="password-reset"),
    path(
        "password/reset/confirm/", PasswordResetConfirmView.as_view(), name="password-reset-confirm"
    ),
    path("branding/<str:tenant_id>/", TenantBrandingView.as_view(), name="tenant-branding"),
    path("branding/<str:pk>/update/", TenantUpdateView.as_view(), name="tenant-update"),
    path("impersonate/<int:target_user_id>/", ImpersonateUserView.as_view(), name="impersonate"),
    path("all/", UserListView.as_view(), name="user-list"),
    path("tenants/all/", TenantListView.as_view(), name="tenant-list"),
    path("tenants/public/", PublicTenantListView.as_view(), name="tenant-list-public"),
    path("audit-log/", AuditLogListView.as_view(), name="audit-log-list"),
    path("create/", UserCreateView.as_view(), name="user-create"),
    path("<int:pk>/update/", UserUpdateView.as_view(), name="user-update"),
    path("<int:pk>/delete/", UserDeleteView.as_view(), name="user-delete"),
    path("<int:pk>/detail/", UserDetailView.as_view(), name="user-detail"),
    path("bulk/set-status/", UserBulkSetStatusView.as_view(), name="users-bulk-set-status"),
    path("bulk/change-role/", UserBulkChangeRoleView.as_view(), name="users-bulk-change-role"),
    path("bulk/jobs/<str:job_id>/", UserBulkJobStatusView.as_view(), name="users-bulk-job-status"),
    path("invitation/", InvitationTokenView.as_view(), name="invitation"),
    path("mfa/status/", mfa_status_view, name="mfa-status"),
    path("mfa/setup/", mfa_setup_view, name="mfa-setup"),
    path("mfa/enable/", mfa_enable_view, name="mfa-enable"),
    path("mfa/verify-session/", mfa_verify_session_view, name="mfa-verify-session"),
    path("mfa/disable/", mfa_disable_view, name="mfa-disable"),
    path("me/export/", user_data_export_view, name="user-data-export"),
    path(
        "me/export/<str:job_id>/download/",
        user_data_export_download_view,
        name="user-data-export-download",
    ),
]
