apiVersion: apps/v1
kind: Deployment
metadata:
  name: sport-backend-api
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sport-celery-worker
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sport-celery-worker-simulation
spec:
  replicas: 1
