# Generated by Django 4.2.7 on 2026-04-23 21:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RUN', 'Running'), ('BIKE', 'Cycling'), ('WALK', 'Walking'), ('WHEELCHAIR', 'Wheelchair')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('distance', models.FloatField(default=0.0, help_text='Distance in meters')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_score', models.FloatField(default=0.0)),
                ('route_path', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('tenant_id', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('radius', models.FloatField(help_text='Radius in meters')),
                ('label', models.CharField(default='Home', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_value', models.CharField(max_length=100)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('expiry_date', models.DateTimeField()),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='activities.poi')),
            ],
        ),
    ]
