# Generated by Django 4.2.7 on 2026-04-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["created_at"], name="activities__created_0e5d3c_idx"),
        ),
    ]
