# Generated by Django 4.2.30 on 2026-06-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0013_disk_audit_event"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="diskauditevent",
            new_name="activities__created_121688_idx",
            old_name="activities__created_8a1f2d_idx",
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["tenant", "is_verified"], name="activities__tenant__805056_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["tenant", "created_at"], name="activities__tenant__984a92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["user", "tenant"], name="activities__user_id_e839ad_idx"),
        ),
    ]
