// STITCH Phase 1 — AthleteProfileScreen (refaktor ProfileScreen)
import React from "react";
import { View, Text, ScrollView, Pressable, StyleSheet } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useUnistyles } from "../theme/unistyles";
import { stitchTheme } from "../theme/stitch";
import * as Haptics from "expo-haptics";
const c = stitchTheme.colors;
const sh = { shadowColor: c.onBackground, shadowOffset: { width: 4, height: 4 }, shadowOpacity: 1, shadowRadius: 0, elevation: 8 };
const s = StyleSheet.create({ ct: { flex: 1, backgroundColor: c.background }, h: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 16, borderBottomWidth: 4, borderBottomColor: c.onBackground, backgroundColor: c.surface }, hl: { flexDirection: "row", alignItems: "center", gap: 8 }, av: { width: 40, height: 40, borderRadius: 20, borderWidth: 4, borderColor: c.onBackground, backgroundColor: c.primaryContainer }, ht: { fontSize: 20, fontWeight: "700", color: c.primary, textTransform: "uppercase" }, hero: { backgroundColor: c.parchment, margin: 16, padding: 16, borderWidth: 4, borderColor: c.onBackground, borderRadius: 8, flexDirection: "row", alignItems: "center", gap: 16, ...sh }, hi: { width: 64, height: 64, borderRadius: 32, borderWidth: 4, borderColor: c.onBackground, backgroundColor: c.primaryContainer }, hn: { fontSize: 24, fontWeight: "700", color: c.onBackground }, hs: { fontSize: 14, color: c.secondary }, lvl: { backgroundColor: c.primaryContainer, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 4, borderWidth: 2, borderColor: c.onBackground, alignSelf: "flex-start", marginTop: 6 }, lvlT: { fontSize: 12, fontWeight: "700", color: c.onBackground }, xpBar: { height: 8, backgroundColor: c.surfaceContainerHighest, borderRadius: 4, overflow: "hidden", marginTop: 8 }, xpFill: { height: "100%", backgroundColor: c.primary, width: "95%" }, grid: { flexDirection: "row", flexWrap: "wrap", padding: 16, gap: 8 }, tile: { width: "47%", backgroundColor: c.parchment, padding: 12, borderWidth: 2, borderColor: c.onBackground, borderRadius: 8, ...sh }, tl: { fontSize: 10, fontWeight: "700", color: c.secondary, textTransform: "uppercase" }, tv: { fontSize: 22, fontWeight: "700", color: c.onBackground, marginTop: 4 }, btn: { backgroundColor: c.primaryContainer, padding: 16, borderRadius: 8, borderWidth: 4, borderColor: c.onBackground, marginHorizontal: 16, marginBottom: 8, alignItems: "center", ...sh }, btnT: { fontSize: 16, fontWeight: "700", color: c.onPrimaryContainer } });
interface Props { user?: any; onLogout?: () => void; onTraining?: () => void; onPerformance?: () => void }
export const AthleteProfileScreen: React.FC<Props> = ({ user, onLogout, onTraining, onPerformance }) => { useUnistyles(); return (<SafeAreaView style={s.ct} edges={["top"]}><View style={[s.h, sh]}><View style={s.hl}><View style={s.av} /><Text style={s.ht}>VELO QUEST</Text></View><Text style={{ fontSize: 20 }}>⚙️</Text></View><ScrollView><View style={s.hero}><View style={s.hi} /><View style={{ flex: 1 }}><Text style={s.hn}>{user?.username ?? "RIDER_01"}</Text><Text style={s.hs}>ROAD WARRIOR</Text><View style={s.lvl}><Text style={s.lvlT}>LVL 42</Text></View><View style={s.xpBar}><View style={s.xpFill} /></View><Text style={[s.hs, { marginTop: 4 }]}>XP: 145,200 / 150,000</Text></View></View><View style={s.grid}>{[{ l: "Distance", v: "12,450 km" }, { l: "Elevation", v: "185k" }, { l: "Rides", v: "412" }, { l: "Max Power", v: "1,120W" }].map((m, i) => (<View key={i} style={s.tile}><Text style={s.tl}>{m.l}</Text><Text style={s.tv}>{m.v}</Text></View>))}</View><Pressable style={({ pressed }) => [s.btn, pressed && { opacity: 0.8 }]} onPress={() => { Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium).catch(() => { }); onTraining?.(); }}><Text style={s.btnT}>⏱ Personal Bests</Text></Pressable><Pressable style={({ pressed }) => [s.btn, { backgroundColor: c.primary }]} onPress={() => { Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium).catch(() => { }); onPerformance?.(); }}><Text style={[s.btnT, { color: c.onPrimary }]}>🚲 Gear Garage</Text></Pressable><Pressable style={({ pressed }) => [s.btn, { backgroundColor: c.error }]} onPress={onLogout}><Text style={[s.btnT, { color: c.onError }]}>LOGOUT</Text></Pressable></ScrollView></SafeAreaView>); };
