apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yaml
  - owner.yaml
  - ingress.yaml
  - scaling-config.yaml

commonLabels:
  app.kubernetes.io/part-of: sport-platform
  app.kubernetes.io/version: v2.1.0-gold-master

images:
  - name: sport-backend
    newName: localhost/sport-backend
    newTag: gold-master-v2.1
  - name: sport-owner
    newName: localhost/sport-owner
    newTag: gold-master-v2.1
