#!/usr/bin/env npx tsx
// packages/tokens/build.ts — resolves {primitive.*} references → platform configs
import * as fs from 'fs';
import * as path from 'path';

// ── Types ──────────────────────────────────────────────
interface TokenEntry {
    value: string | number;
    description?: string;
    [key: string]: unknown;
}

interface TokenMap {
    [key: string]: TokenEntry;
}

interface ColorsJSON {
    colors: {
        primitive: TokenMap;
        semantic: TokenMap;
        grandPrix: TokenMap;
        grandPrixNight: TokenMap;
    };
    [key: string]: unknown;
}

// ── Load source ────────────────────────────────────────
const srcPath = path.join(__dirname, 'colors.json');
if (!fs.existsSync(srcPath)) {
    console.error(`ERROR: colors.json not found at ${srcPath}`);
    process.exit(1);
}

const tokens: ColorsJSON = JSON.parse(fs.readFileSync(srcPath, 'utf-8'));

// ── Resolution ─────────────────────────────────────────

/**
 * Resolve {primitive.xxx} references → actual hex values.
 * Supports recursive resolution (references within resolved values).
 * Throws on circular or unresolved references.
 */
function resolve(
    value: string,
    primitives: TokenMap,
    seen: Set<string> = new Set()
): string {
    return value.replace(/\{primitive\.(\w+)\}/g, (_match, key: string) => {
        if (!primitives[key]) {
            throw new Error(
                `Unresolved token reference: {primitive.${key}} in "${value}"`
            );
        }

        const refPath = `primitive.${key}`;
        if (seen.has(refPath)) {
            throw new Error(
                `Circular token reference detected: {primitive.${key}} → ${[...seen].join(' → ')}`
            );
        }

        const rawValue = String(primitives[key].value);
        // Recursively resolve in case primitive values reference other primitives
        const nextSeen = new Set(seen);
        nextSeen.add(refPath);
        return resolve(rawValue, primitives, nextSeen);
    });
}

/** Flatten a theme section into { [tokenName]: hexString } */
function flattenTheme(
    theme: TokenMap,
    primitives: TokenMap
): Record<string, string> {
    const result: Record<string, string> = {};
    for (const [key, entry] of Object.entries(theme)) {
        result[key] = resolve(String(entry.value), primitives);
    }
    return result;
}

// ── Check mode ─────────────────────────────────────────
const isCheck = process.argv.includes('--check');

// ── Build output ───────────────────────────────────────
const { primitive, semantic, grandPrix, grandPrixNight } = tokens.colors;

// Resolve semantics (they reference primitives)
const resolvedSemantic: Record<string, string> = {};
for (const [key, entry] of Object.entries(semantic)) {
    resolvedSemantic[key] = resolve(String(entry.value), primitive);
}

const output = {
    primitive: Object.fromEntries(
        Object.entries(primitive).map(([k, v]) => [k, v.value])
    ) as Record<string, string | number>,
    semantic: resolvedSemantic,
    grandPrix: flattenTheme(grandPrix, primitive),
    grandPrixNight: flattenTheme(grandPrixNight, primitive),
};

// ── Ensure output directory ────────────────────────────
const outDir = path.join(__dirname, 'generated');

// ── Check mode: verify outputs exist and are not stale ─
if (isCheck) {
    const tsOut = path.join(outDir, 'restyle-colors.ts');
    const jsonOut = path.join(outDir, 'colors-flat.json');

    const srcStat = fs.statSync(srcPath);
    let stale = false;

    for (const outPath of [tsOut, jsonOut]) {
        if (!fs.existsSync(outPath)) {
            console.error(`ERROR: Missing generated file: ${outPath}`);
            stale = true;
        } else {
            const outStat = fs.statSync(outPath);
            if (outStat.mtime < srcStat.mtime) {
                console.error(`ERROR: Stale generated file (source newer): ${outPath}`);
                stale = true;
            }
        }
    }

    if (stale) {
        console.error('\n❌ tokens:check FAILED — run "npm run tokens:build" to regenerate.');
        process.exit(1);
    }

    console.log('✅ tokens:check passed — generated files are up-to-date.');
    process.exit(0);
}

if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
}

// ── Write TypeScript constants ─────────────────────────
const tsHeader = `// AUTO-GENERATED by packages/tokens/build.ts — DO NOT EDIT
// Run: pnpm tokens:build
// Source: packages/tokens/colors.json
`;

const restyleOutput =
    tsHeader +
    `export const colors = ${JSON.stringify(output, null, 2)} as const;\n`;

fs.writeFileSync(path.join(outDir, 'restyle-colors.ts'), restyleOutput);
console.log(`  ✓  generated/restyle-colors.ts`);

// ── Write flat JSON ────────────────────────────────────
fs.writeFileSync(
    path.join(outDir, 'colors-flat.json'),
    JSON.stringify(output, null, 2) + '\n'
);
console.log(`  ✓  generated/colors-flat.json`);

// ── Summary ────────────────────────────────────────────
const themeCounts = {
    primitive: Object.keys(output.primitive).length,
    semantic: Object.keys(output.semantic).length,
    grandPrix: Object.keys(output.grandPrix).length,
    grandPrixNight: Object.keys(output.grandPrixNight).length,
};

console.log(
    `\n✅ Token resolution complete — ${themeCounts.primitive} primitives, ${themeCounts.semantic} semantic, ${themeCounts.grandPrix} grandPrix, ${themeCounts.grandPrixNight} grandPrixNight tokens resolved`
);
