#!/usr/bin/env npx tsx
// packages/tokens/build.ts — resolves repo-owned design tokens into reviewable artifacts
import * as fs from 'fs';
import * as path from 'path';

interface TokenEntry {
    value: string | number;
    description?: string;
    [key: string]: unknown;
}

interface TokenMap {
    [key: string]: TokenEntry;
}

interface ColorsJSON {
    colors: {
        primitive: TokenMap;
        semantic: TokenMap;
        grandPrix: TokenMap;
        grandPrixNight: TokenMap;
    };
    spacing?: unknown;
    typography?: unknown;
    borders?: unknown;
    shadows?: unknown;
    [key: string]: unknown;
}

const srcPath = path.join(__dirname, 'colors.json');
if (!fs.existsSync(srcPath)) {
    console.error(`ERROR: colors.json not found at ${srcPath}`);
    process.exit(1);
}

const tokens: ColorsJSON = JSON.parse(fs.readFileSync(srcPath, 'utf-8'));

function resolve(
    value: string,
    primitives: TokenMap,
    seen: Set<string> = new Set()
): string {
    return value.replace(/\{primitive\.(\w+)\}/g, (_match, key: string) => {
        if (!primitives[key]) {
            throw new Error(
                `Unresolved token reference: {primitive.${key}} in "${value}"`
            );
        }

        const refPath = `primitive.${key}`;
        if (seen.has(refPath)) {
            throw new Error(
                `Circular token reference detected: {primitive.${key}} → ${[...seen].join(' → ')}`
            );
        }

        const nextSeen = new Set(seen);
        nextSeen.add(refPath);
        return resolve(String(primitives[key].value), primitives, nextSeen);
    });
}

function flattenTheme(
    theme: TokenMap,
    primitives: TokenMap
): Record<string, string> {
    const result: Record<string, string> = {};
    for (const [key, entry] of Object.entries(theme)) {
        result[key] = resolve(String(entry.value), primitives);
    }
    return result;
}

const { primitive, semantic, grandPrix, grandPrixNight } = tokens.colors;

const resolvedSemantic: Record<string, string> = {};
for (const [key, entry] of Object.entries(semantic)) {
    resolvedSemantic[key] = resolve(String(entry.value), primitive);
}

const output = {
    primitive: Object.fromEntries(
        Object.entries(primitive).map(([key, value]) => [key, value.value])
    ) as Record<string, string | number>,
    semantic: resolvedSemantic,
    grandPrix: flattenTheme(grandPrix, primitive),
    grandPrixNight: flattenTheme(grandPrixNight, primitive),
};

function collection(
    name: string,
    modes: Record<string, Record<string, string | number>>
) {
    return {
        name,
        modes: Object.entries(modes).map(([mode, values]) => ({
            name: mode,
            variables: Object.entries(values).map(([tokenName, value]) => ({
                name: tokenName,
                resolvedType: typeof value === 'number' ? 'FLOAT' : 'COLOR',
                value,
            })),
        })),
    };
}

/**
 * Repository-owned interchange for optional Figma synchronization.
 *
 * This is deliberately not a Figma API response and does not require a paid
 * Figma plan. A future sync adapter may translate this stable artifact into
 * Variables API calls when credentials/plan support are available.
 */
const figmaBridge = {
    schemaVersion: 1,
    authority: 'github',
    source: 'packages/tokens/colors.json',
    generatedBy: 'packages/tokens/build.ts',
    collections: [
        collection('4VELO / Primitive', { Default: output.primitive }),
        collection('4VELO / Semantic', { Default: output.semantic }),
        collection('4VELO / Theme', {
            Day: output.grandPrix,
            Night: output.grandPrixNight,
        }),
    ],
    nonColorTokens: {
        spacing: tokens.spacing ?? null,
        typography: tokens.typography ?? null,
        borders: tokens.borders ?? null,
        shadows: tokens.shadows ?? null,
    },
};

const outDir = path.join(__dirname, 'generated');
const tsHeader = `// AUTO-GENERATED by packages/tokens/build.ts — DO NOT EDIT
// Run: pnpm tokens:build
// Source: packages/tokens/colors.json
`;

const expectedFiles = new Map<string, string>([
    [
        path.join(outDir, 'restyle-colors.ts'),
        tsHeader + `export const colors = ${JSON.stringify(output, null, 2)} as const;\n`,
    ],
    [
        path.join(outDir, 'colors-flat.json'),
        JSON.stringify(output, null, 2) + '\n',
    ],
    [
        path.join(outDir, 'figma-variables-bridge.json'),
        JSON.stringify(figmaBridge, null, 2) + '\n',
    ],
]);

const isCheck = process.argv.includes('--check');

if (isCheck) {
    let stale = false;
    for (const [outPath, expected] of expectedFiles) {
        if (!fs.existsSync(outPath)) {
            console.error(`ERROR: Missing generated file: ${outPath}`);
            stale = true;
            continue;
        }

        const actual = fs.readFileSync(outPath, 'utf-8');
        if (actual !== expected) {
            console.error(`ERROR: Stale generated file content: ${outPath}`);
            stale = true;
        }
    }

    if (stale) {
        console.error('\n❌ tokens:check FAILED — run "pnpm tokens:build" to regenerate.');
        process.exit(1);
    }

    console.log('✅ tokens:check passed — generated files match repository token source.');
    process.exit(0);
}

fs.mkdirSync(outDir, { recursive: true });

for (const [outPath, expected] of expectedFiles) {
    fs.writeFileSync(outPath, expected);
    console.log(`  ✓  generated/${path.basename(outPath)}`);
}

const themeCounts = {
    primitive: Object.keys(output.primitive).length,
    semantic: Object.keys(output.semantic).length,
    grandPrix: Object.keys(output.grandPrix).length,
    grandPrixNight: Object.keys(output.grandPrixNight).length,
};

console.log(
    `\n✅ Token resolution complete — ${themeCounts.primitive} primitives, ${themeCounts.semantic} semantic, ${themeCounts.grandPrix} grandPrix, ${themeCounts.grandPrixNight} grandPrixNight tokens resolved`
);
console.log('✅ Figma bridge regenerated from GitHub-owned token source.');
