#!/usr/bin/env python3
"""
Copy repo assets/generated into mobile bundle and emit TypeScript manifest.

Usage:
  python scripts/bundle_mobile_assets.py
  python scripts/bundle_mobile_assets.py --dry-run
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from datetime import UTC, datetime
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

from asset_definitions import get_all_assets  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = REPO_ROOT / "assets" / "generated"
MOBILE_DIR = REPO_ROOT / "mobile" / "assets" / "generated"
MANIFEST_TS = REPO_ROOT / "mobile" / "src" / "assets" / "manifest.ts"

COPY_EXTENSIONS = {".png", ".svg", ".json"}


def existing_source_files() -> list[Path]:
    if not SOURCE_DIR.exists():
        return []
    return [p for p in SOURCE_DIR.rglob("*") if p.is_file() and p.suffix.lower() in COPY_EXTENSIONS]


def write_manifest_ts(copied: list[str]) -> str:
    lines = [
        "/** Auto-generated by scripts/bundle_mobile_assets.py — do not edit manually. */",
        "",
        "export type MobileAssetCategory =",
        "  | 'icon'",
        "  | 'sprite'",
        "  | 'expression'",
        "  | 'texture'",
        "  | 'environment'",
        "  | 'particle'",
        "  | 'sound';",
        "",
        "export interface MobileAssetEntry {",
        "  id: string;",
        "  category: MobileAssetCategory;",
        "  relativePath: string;",
        "  bundled: boolean;",
        "}",
        "",
        "/** Catalog from asset_definitions.py; bundled=true when file exists in mobile/assets/generated. */",
        "export const MOBILE_ASSET_CATALOG: MobileAssetEntry[] = [",
    ]
    bundled_set = set(copied)
    for asset in get_all_assets():
        rel = asset["output_path"].replace("\\", "/")
        cat = asset["category"]
        if cat == "sound":
            cat_literal = "sound"
        elif cat in ("environment", "particle"):
            cat_literal = cat
        else:
            cat_literal = cat
        lines.append(
            f"  {{ id: '{asset['id']}', category: '{cat_literal}', "
            f"relativePath: '{rel}', bundled: {str(rel in bundled_set).lower()} }},"
        )
    lines.append("];")
    lines.append("")
    lines.append("export function getBundledAssets(): MobileAssetEntry[] {")
    lines.append("  return MOBILE_ASSET_CATALOG.filter((a) => a.bundled);")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Bundle generated assets into mobile/")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    files = existing_source_files()
    if not files:
        print(f"No assets under {SOURCE_DIR}; writing manifest with bundled=false entries.")
    copied_rel: list[str] = []
    if not args.dry_run:
        MOBILE_DIR.mkdir(parents=True, exist_ok=True)
        MANIFEST_TS.parent.mkdir(parents=True, exist_ok=True)

    for src in files:
        rel = src.relative_to(SOURCE_DIR).as_posix()
        dst = MOBILE_DIR / rel
        if args.dry_run:
            print(f"DRY {rel}")
        else:
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            print(f"COPY {rel}")
        copied_rel.append(rel)

    manifest_json = {
        "bundled_at": datetime.now(UTC).isoformat(),
        "source": str(SOURCE_DIR),
        "mobile_target": str(MOBILE_DIR),
        "files": sorted(copied_rel),
    }
    if not args.dry_run:
        (MOBILE_DIR / "BUNDLE_MANIFEST.json").write_text(
            json.dumps(manifest_json, indent=2),
            encoding="utf-8",
        )
        MANIFEST_TS.write_text(write_manifest_ts(copied_rel), encoding="utf-8")
        print(f"Wrote {MANIFEST_TS}")

    print(f"Bundled {len(copied_rel)} file(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
