/** Auto-generated by scripts/bundle_mobile_assets.py — do not edit manually. */

export type MobileAssetCategory =
  | 'icon'
  | 'sprite'
  | 'expression'
  | 'texture'
  | 'environment'
  | 'particle'
  | 'sound';

export interface MobileAssetEntry {
  id: string;
  category: MobileAssetCategory;
  relativePath: string;
  bundled: boolean;
}

/** Catalog from asset_definitions.py; bundled=true when file exists in mobile/assets/generated. */
export const MOBILE_ASSET_CATALOG: MobileAssetEntry[] = [
  { id: 'tab_home', category: 'icon', relativePath: 'icons/tab_home.png', bundled: true },
  { id: 'tab_history', category: 'icon', relativePath: 'icons/tab_history.png', bundled: true },
  { id: 'tab_ranking', category: 'icon', relativePath: 'icons/tab_ranking.png', bundled: true },
  { id: 'tab_rewards', category: 'icon', relativePath: 'icons/tab_rewards.png', bundled: true },
  { id: 'tab_profile', category: 'icon', relativePath: 'icons/tab_profile.png', bundled: true },
  { id: 'grade_s', category: 'icon', relativePath: 'icons/grade_s.png', bundled: true },
  { id: 'grade_a', category: 'icon', relativePath: 'icons/grade_a.png', bundled: true },
  { id: 'grade_b', category: 'icon', relativePath: 'icons/grade_b.png', bundled: true },
  { id: 'grade_c', category: 'icon', relativePath: 'icons/grade_c.png', bundled: true },
  { id: 'grade_d', category: 'icon', relativePath: 'icons/grade_d.png', bundled: true },
  { id: 'power_speed', category: 'icon', relativePath: 'icons/power_speed.png', bundled: true },
  { id: 'power_shield', category: 'icon', relativePath: 'icons/power_shield.png', bundled: true },
  { id: 'power_double_xp', category: 'icon', relativePath: 'icons/power_double_xp.png', bundled: true },
  { id: 'power_gps', category: 'icon', relativePath: 'icons/power_gps.png', bundled: true },
  { id: 'currency_xp', category: 'icon', relativePath: 'icons/currency_xp.png', bundled: true },
  { id: 'currency_coin', category: 'icon', relativePath: 'icons/currency_coin.png', bundled: true },
  { id: 'currency_energy', category: 'icon', relativePath: 'icons/currency_energy.png', bundled: true },
  { id: 'cyclist_idle', category: 'expression', relativePath: 'expressions/cyclist_idle.png', bundled: true },
  { id: 'cyclist_happy', category: 'expression', relativePath: 'expressions/cyclist_happy.png', bundled: true },
  { id: 'cyclist_tired', category: 'expression', relativePath: 'expressions/cyclist_tired.png', bundled: true },
  { id: 'cyclist_victory', category: 'expression', relativePath: 'expressions/cyclist_victory.png', bundled: true },
  { id: 'cyclist_sheet', category: 'sprite', relativePath: 'sprites/cyclist_sheet.png', bundled: true },
  { id: 'env_sky_day', category: 'environment', relativePath: 'environment/sky_day.png', bundled: true },
  { id: 'env_hills_far', category: 'environment', relativePath: 'environment/hills_far.png', bundled: true },
  { id: 'env_town_mid', category: 'environment', relativePath: 'environment/town_mid.png', bundled: true },
  { id: 'env_road_near', category: 'environment', relativePath: 'environment/road_near.png', bundled: true },
  { id: 'particle_atlas', category: 'particle', relativePath: 'particles/particle_atlas.png', bundled: true },
  { id: 'parchment_grain', category: 'texture', relativePath: 'textures/parchment_grain.png', bundled: true },
  { id: 'metal_plate', category: 'texture', relativePath: 'textures/metal_plate.png', bundled: true },
  { id: 'wood_grain', category: 'texture', relativePath: 'textures/wood_grain.png', bundled: true },
  { id: 'app_icon', category: 'icon', relativePath: 'icon.png', bundled: false },
  { id: 'splash_icon', category: 'icon', relativePath: 'splash-icon.png', bundled: false },
  { id: 'adaptive_icon', category: 'icon', relativePath: 'adaptive-icon.png', bundled: false },
  { id: 'favicon', category: 'icon', relativePath: 'favicon.png', bundled: false },
  { id: 'sfx_params', category: 'sound', relativePath: 'sounds/sfx_params.json', bundled: true },
];

export function getBundledAssets(): MobileAssetEntry[] {
  return MOBILE_ASSET_CATALOG.filter((a) => a.bundled);
}
