/**
 * visionAssets.ts — OPTIONAL registry for vision-parity art (Faza D).
 *
 * The PNGs are produced by the asset generator (scripts/asset_definitions.py
 * -> generate_assets.py). Until they exist in assets/generated, every entry
 * stays `undefined` and the composition components render a pixel fallback.
 * After generating, replace `undefined` with a static `require(...)` — the
 * components upgrade automatically with no further wiring.
 *
 * Metro only bundles STATIC require() paths, so we must not require files that
 * do not exist yet; hence the explicit `undefined` placeholders.
 */
import type { ImageSourcePropType } from 'react-native';

export type CrestKey = 'gdansk' | 'katowice' | 'lublin' | 'siedlce' | 'warszawa';
export type DeptKey = 'it' | 'marketing' | 'hr' | 'sales';

const CREST: Record<CrestKey, ImageSourcePropType | undefined> = {
  // AUTO-WIRE:CREST:START
  gdansk: require('../../assets/generated/icons/crest_gdansk.png'),
  katowice: require('../../assets/generated/icons/crest_katowice.png'),
  lublin: require('../../assets/generated/icons/crest_lublin.png'),
  siedlce: require('../../assets/generated/icons/crest_siedlce.png'),
  warszawa: require('../../assets/generated/icons/crest_warszawa.png'),
  // AUTO-WIRE:CREST:END
};

const DEPT: Record<DeptKey, ImageSourcePropType | undefined> = {
  // AUTO-WIRE:DEPT:START
  it: require('../../assets/generated/icons/dept_it.png'),
  marketing: require('../../assets/generated/icons/dept_marketing.png'),
  hr: require('../../assets/generated/icons/dept_hr.png'),
  sales: require('../../assets/generated/icons/dept_sales.png'),
  // AUTO-WIRE:DEPT:END
};

const ACHIEVEMENT: Record<string, ImageSourcePropType | undefined> = {
  // AUTO-WIRE:ACHIEVEMENT:START
  ach_100km: require('../../assets/generated/icons/ach_100km.png'),
  ach_10rides: require('../../assets/generated/icons/ach_10rides.png'),
  ach_500m: require('../../assets/generated/icons/ach_500m.png'),
  ach_kom: require('../../assets/generated/icons/ach_kom.png'),
  ach_5h: require('../../assets/generated/icons/ach_5h.png'),
  ach_endurance: require('../../assets/generated/icons/ach_endurance.png'),
  ach_1000kcal: require('../../assets/generated/icons/ach_1000kcal.png'),
  ach_7days: require('../../assets/generated/icons/ach_7days.png'),
  ach_explorer: require('../../assets/generated/icons/ach_explorer.png'),
  ach_passion: require('../../assets/generated/icons/ach_passion.png'),
  // AUTO-WIRE:ACHIEVEMENT:END
};

export const VISION_BANNERS: Record<string, ImageSourcePropType | undefined> = {
  // AUTO-WIRE:BANNERS:START
  city_lublin: require('../../assets/generated/environment/banner_city_lublin.png'),
  finish_meta: require('../../assets/generated/environment/finish_meta.png'),
  avatar_frame: require('../../assets/generated/icons/avatar_frame.png'),
  frame_ornate: require('../../assets/generated/textures/frame_ornate.png'),
  sky_sunset: require('../../assets/generated/environment/sky_sunset.png'),
  sky_night: require('../../assets/generated/environment/sky_night.png'),
  // AUTO-WIRE:BANNERS:END
};

/**
 * HUD action icons — pixel-art stop / pause / play.
 * Generated by the asset pipeline as 24×24 icons; fall back to View glifs
 * when PNGs are absent (current state). Add `require()` entries once generated.
 */
export const HUD_ACTION_ICONS: Record<string, ImageSourcePropType | undefined> = {
  // AUTO-WIRE:HUD_ACTIONS:START
  stop: require('../../assets/generated/icons/hud_stop.png'),
  pause: require('../../assets/generated/icons/hud_pause.png'),
  play: require('../../assets/generated/icons/hud_play.png'),
  // AUTO-WIRE:HUD_ACTIONS:END
};

function normalize(value: string): string {
  return value
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // strip diacritics
    .replace(/[^a-z]/g, ''); // drop spaces, hyphens, "-city", etc. collapse
}

/** Map a tenant id or display name to a crest source (undefined until generated). */
export function crestForTenant(idOrName: string | null | undefined): ImageSourcePropType | undefined {
  if (!idOrName) return undefined;
  const n = normalize(idOrName);
  const key = (Object.keys(CREST) as CrestKey[]).find((k) => n.includes(k));
  return key ? CREST[key] : undefined;
}

/** Map a department name to a team icon (undefined until generated). */
export function deptIconFor(name: string | null | undefined): ImageSourcePropType | undefined {
  if (!name) return undefined;
  const n = normalize(name);
  if (n.includes('it') || n.includes('dev')) return DEPT.it;
  if (n.includes('market')) return DEPT.marketing;
  if (n.includes('hr') || n.includes('kadr')) return DEPT.hr;
  if (n.includes('sprzeda') || n.includes('sales')) return DEPT.sales;
  return undefined;
}

export function achievementIcon(id: string): ImageSourcePropType | undefined {
  return ACHIEVEMENT[id];
}

/** Two-letter fallback initials for a crest when its PNG is absent. */
export function crestInitials(name: string): string {
  return name.trim().slice(0, 2).toUpperCase();
}
