export const appearanceCopy = {
  pl: {
    title: 'Wygląd', subtitle: 'Ta sama jazda. Twój styl.', back: 'Wróć', theme: 'Motyw',
    light: 'Jasny', dark: 'Ciemny', system: 'Systemowy', mode: 'Tryb kolorystyczny',
    contrast: 'Wysoki kontrast', preview: 'Podgląd · przykładowe dane', speed: 'Prędkość',
    distance: 'Dystans', time: 'Czas', start: 'Rozpocznij jazdę', apply: 'Zastosuj', cancel: 'Anuluj',
    import: 'Sprawdź i pokaż podgląd', importTitle: 'Dodaj motyw',
    importHint: 'Wklej paczkę JSON (do 16 384 znaków). Nowy motyw musi mieć unikalne id.',
    export: 'Eksportuj JSON', remove: 'Usuń motyw', removeConfirm: 'Usunąć tę paczkę? Aktywny motyw zostanie zastąpiony Roadbookiem.',
    saved: 'Wygląd zapisany.', temporary: 'Brak trwałego magazynu. Zmiany działają tylko w tej sesji.',
    recovered: 'Przywrócono bezpieczny wygląd po błędzie zapisanych ustawień.',
    format: 'Nieobsługiwany lub uszkodzony format motywu.', contrastError: 'Motyw nie spełnia wymagań kontrastu.',
    limit: 'Przekroczono limit rozmiaru lub 10 własnych motywów.', duplicate: 'Motyw o tym id już istnieje.',
    missing: 'Ten motyw nie jest dostępny.', storage: 'Nie zapisano zmian. Poprzedni motyw pozostaje aktywny.',
    exportError: 'Nie udało się udostępnić motywu.',
  },
  en: {
    title: 'Appearance', subtitle: 'The same ride. Your style.', back: 'Back', theme: 'Theme',
    light: 'Light', dark: 'Dark', system: 'System', mode: 'Colour mode',
    contrast: 'High contrast', preview: 'Preview · sample data', speed: 'Speed',
    distance: 'Distance', time: 'Time', start: 'Start ride', apply: 'Apply', cancel: 'Cancel',
    import: 'Validate and preview', importTitle: 'Add a theme',
    importHint: 'Paste a JSON pack (up to 16,384 characters). A new theme needs a unique id.',
    export: 'Export JSON', remove: 'Remove theme', removeConfirm: 'Remove this pack? An active theme will fall back to Roadbook.',
    saved: 'Appearance saved.', temporary: 'Persistent storage is unavailable. Changes last for this session only.',
    recovered: 'Safe appearance restored after a stored-settings error.',
    format: 'Unsupported or malformed theme pack.', contrastError: 'This theme does not meet contrast requirements.',
    limit: 'Pack size or the limit of 10 custom themes exceeded.', duplicate: 'A theme with this id already exists.',
    missing: 'This theme is unavailable.', storage: 'Changes were not saved. The previous theme remains active.',
    exportError: 'The theme could not be shared.',
  },
};
