apiVersion: v1
kind: Service
metadata:
  name: sport-traccar
  labels:
    app: sport-traccar
spec:
  selector:
    app: sport-traccar
  ports:
    - name: web
      port: 8082
      targetPort: 8082
    - name: gps
      port: 5055
      targetPort: 5055
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sport-traccar
  labels:
    app: sport-traccar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sport-traccar
  template:
    metadata:
      labels:
        app: sport-traccar
    spec:
      containers:
        - name: traccar
          image: traccar/traccar:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              name: web
            - containerPort: 5055
              name: gps
