# Generated by Django 4.2.7 on 2026-04-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='config_json',
            field=models.JSONField(blank=True, default=dict, help_text='Per-tenant configuration: brouter_validation, normalization_factor, allowed_sports, push_notification_key, etc.'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='white_label_domain',
            field=models.CharField(blank=True, help_text='Custom domain for white-label deployments (e.g. wellness.acme.com)', max_length=200),
        ),
    ]
