# Generated by Django 4.2.7 on 2026-04-24 00:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_tenantprofile_config_json_and_more"),
    ]

    operations = []
